import type { CodeSnippet, LearningPath, Note, Resource, Topic } from '../models/types';

export interface PathBackup {
  version: 1;
  type: 'learning-path';
  learningPath: LearningPath;
  topics: Topic[];
  notes: Note[];
  snippets: CodeSnippet[];
  resources: Resource[];
}

const now = Date.now();

export const csTemplates: PathBackup[] = [
  {
    version: 1,
    type: 'learning-path',
    learningPath: {
      id: 'template-dsa',
      title: 'Data Structures & Algorithms',
      description: 'Master arrays, lists, trees, graphs, and algorithmic problem-solving techniques.',
      icon: 'Binary',
      color: '#38bdf8',
      targetRoles: ['Software Engineer', 'Backend Engineer', 'Frontend Engineer'],
      minimumLevel: 'Fresher',
      maximumLevel: 'Senior',
      createdAt: now,
    },
    topics: [
      {
        id: 'dsa-arrays-hashing',
        learningPathId: 'template-dsa',
        parentId: null,
        title: 'Arrays & Hashing',
        description: 'Sequentially stored collections and key-value mapping mechanics.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-two-pointers',
        learningPathId: 'template-dsa',
        parentId: 'dsa-arrays-hashing',
        title: 'Two Pointers',
        description: 'Linear search optimization using left/right pointers.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-sliding-window',
        learningPathId: 'template-dsa',
        parentId: 'dsa-arrays-hashing',
        title: 'Sliding Window',
        description: 'Subarray problem-solving with dynamic sizing.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-linked-lists',
        learningPathId: 'template-dsa',
        parentId: null,
        title: 'Linked Lists',
        description: 'Singly, doubly, and circular lists. Pointer manipulation.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-lists-types',
        learningPathId: 'template-dsa',
        parentId: 'dsa-linked-lists',
        title: 'Singly & Doubly Lists',
        description: 'Understanding node linking and pointer direction traversal.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-lists-pointers',
        learningPathId: 'template-dsa',
        parentId: 'dsa-linked-lists',
        title: 'Fast & Slow Pointers',
        description: 'Floyd\'s cycle detection and middle node algorithms.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-stacks-queues',
        learningPathId: 'template-dsa',
        parentId: null,
        title: 'Stacks & Queues',
        description: 'LIFO and FIFO linear collections.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-min-stack',
        learningPathId: 'template-dsa',
        parentId: 'dsa-stacks-queues',
        title: 'Min Stack',
        description: 'Design a stack that retrieves the minimum element in O(1) time.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-queue-stacks',
        learningPathId: 'template-dsa',
        parentId: 'dsa-stacks-queues',
        title: 'Queue using Stacks',
        description: 'Implement a FIFO queue using LIFO stack nodes.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-trees',
        learningPathId: 'template-dsa',
        parentId: null,
        title: 'Trees',
        description: 'Hierarchical node structures.',
        order: 3,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-tree-traversal',
        learningPathId: 'template-dsa',
        parentId: 'dsa-trees',
        title: 'Traversal (DFS/BFS)',
        description: 'Inorder, preorder, postorder, and level-order traversals.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-bst',
        learningPathId: 'template-dsa',
        parentId: 'dsa-trees',
        title: 'Binary Search Trees',
        description: 'Operations (lookup, insert, delete) and properties.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-trie',
        learningPathId: 'template-dsa',
        parentId: 'dsa-trees',
        title: 'Tries (Prefix Trees)',
        description: 'Optimizing string searches and autocomplete features.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-graphs',
        learningPathId: 'template-dsa',
        parentId: null,
        title: 'Graphs',
        description: 'Networks of vertices connected by edges.',
        order: 4,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-graph-bfs-dfs',
        learningPathId: 'template-dsa',
        parentId: 'dsa-graphs',
        title: 'BFS/DFS Traversal',
        description: 'Exploring neighbors and diving deep in graph structures.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-dijkstra',
        learningPathId: 'template-dsa',
        parentId: 'dsa-graphs',
        title: 'Dijkstra\'s Shortest Path',
        description: 'Single-source shortest path using priority queues.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-topological-sort',
        learningPathId: 'template-dsa',
        parentId: 'dsa-graphs',
        title: 'Topological Sort',
        description: 'Linear ordering of DAG nodes for dependency resolution.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-sorting-searching',
        learningPathId: 'template-dsa',
        parentId: null,
        title: 'Sorting & Searching',
        description: 'Efficient element arrangement and lookup.',
        order: 5,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-binary-search',
        learningPathId: 'template-dsa',
        parentId: 'dsa-sorting-searching',
        title: 'Binary Search',
        description: 'Logarithmic search on sorted arrays.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-quick-merge',
        learningPathId: 'template-dsa',
        parentId: 'dsa-sorting-searching',
        title: 'Quick/Merge Sort',
        description: 'Divide and conquer sorting algorithms.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-dp',
        learningPathId: 'template-dsa',
        parentId: null,
        title: 'Dynamic Programming',
        description: 'Solving complex problems by breaking them into overlapping subproblems.',
        order: 6,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-dp-memo',
        learningPathId: 'template-dsa',
        parentId: 'dsa-dp',
        title: 'Memoization vs Tabulation',
        description: 'Top-down caching vs bottom-up iterative state tables.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'dsa-dp-knapsack',
        learningPathId: 'template-dsa',
        parentId: 'dsa-dp',
        title: '0/1 Knapsack',
        description: 'Classical optimization problem using state array tables.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
    ],
    notes: [
      {
        id: 'note-dsa-arrays',
        topicId: 'dsa-arrays-hashing',
        markdown: '# Arrays & Hashing\n\nArrays store elements sequentially, offering O(1) random access.\n\nHash Maps map keys to values using a hashing function, offering O(1) average lookup/insertion. Watch out for hash collisions and load factors!',
        updatedAt: now,
      },
    ],
    snippets: [
      {
        id: 'snippet-dsa-two-sum',
        topicId: 'dsa-arrays-hashing',
        filename: 'twoSum.ts',
        language: 'typescript',
        code: `export function twoSum(nums: number[], target: number): number[] {\n  const map = new Map<number, number>();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (map.has(complement)) {\n      return [map.get(complement)!, i];\n    }\n    map.set(nums[i], i);\n  }\n  return [];\n}`,
        updatedAt: now,
      },
    ],
    resources: [],
  },
  {
    version: 1,
    type: 'learning-path',
    learningPath: {
      id: 'template-sysdesign',
      title: 'System Design',
      description: 'Learn scaling, caching, sharding, message queues, and designing durable systems.',
      icon: 'Server',
      color: '#f87171',
      targetRoles: ['Software Architect', 'Backend Engineer', 'Full Stack Engineer'],
      minimumLevel: 'Mid',
      maximumLevel: 'Architect',
      createdAt: now,
    },
    topics: [
      {
        id: 'sd-scaling-basics',
        learningPathId: 'template-sysdesign',
        parentId: null,
        title: 'Scaling Fundamentals',
        description: 'Vertical vs horizontal scaling, and latency vs throughput.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-scale-types',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-scaling-basics',
        title: 'Vertical/Horizontal Scaling',
        description: 'Resource upgrades vs distributing workloads across machines.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-load-balancing',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-scaling-basics',
        title: 'Load Balancing',
        description: 'Nginx, HAProxy, Round Robin, and Consistent Hashing.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-high-availability',
        learningPathId: 'template-sysdesign',
        parentId: null,
        title: 'High Availability',
        description: 'Building fail-safe and fault-tolerant architecture.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-monolith-micro',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-high-availability',
        title: 'Monoliths vs Microservices',
        description: 'Comparing deployment models and coupling.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-consistent-hash',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-high-availability',
        title: 'Consistent Hashing',
        description: 'Minimizing key remapping during database resizing.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-caching',
        learningPathId: 'template-sysdesign',
        parentId: null,
        title: 'Caching',
        description: 'Temporary high-speed storage.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-redis-memcached',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-caching',
        title: 'Redis/Memcached',
        description: 'Comparison of key-value stores.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-eviction',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-caching',
        title: 'Cache Eviction Policies',
        description: 'LRU, LFU, and write-through/write-back mechanics.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-cdn',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-caching',
        title: 'CDN',
        description: 'Caching static assets geographically closer to users.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-database-scale',
        learningPathId: 'template-sysdesign',
        parentId: null,
        title: 'Database Scale',
        description: 'Techniques to scale persistent storage.',
        order: 3,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-db-replication',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-database-scale',
        title: 'Replication',
        description: 'Leader-follower model, failovers, and lag.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-sharding',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-database-scale',
        title: 'Sharding',
        description: 'Horizontal database sharding strategies.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-cap',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-database-scale',
        title: 'SQL vs NoSQL / CAP',
        description: 'Consistency, Availability, and Partition Tolerance tradeoffs.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-async-systems',
        learningPathId: 'template-sysdesign',
        parentId: null,
        title: 'Async Systems',
        description: 'Decoupled system communication.',
        order: 4,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-queues',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-async-systems',
        title: 'Message Queues (Kafka/RabbitMQ)',
        description: 'Comparing publish-subscribe and routing brokers.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'sd-event-driven',
        learningPathId: 'template-sysdesign',
        parentId: 'sd-async-systems',
        title: 'Event-Driven Architecture',
        description: 'Real-time asynchronous pub-sub patterns.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
    ],
    notes: [
      {
        id: 'note-sd-scaling',
        topicId: 'sd-scaling-basics',
        markdown: '# Scaling Fundamentals\n\n* **Vertical Scaling**: Adding CPU/RAM to a single server. Limits: physical hardware cap, single point of failure.\n* **Horizontal Scaling**: Adding more commodity servers to the pool. Requires load balancing.',
        updatedAt: now,
      },
    ],
    snippets: [],
    resources: [],
  },
  {
    version: 1,
    type: 'learning-path',
    learningPath: {
      id: 'template-os',
      title: 'Operating Systems',
      description: 'Dive into processes, threads, virtual memory, scheduling, and concurrency control.',
      icon: 'Cpu',
      color: '#fbbf24',
      targetRoles: ['Backend Engineer', 'Embedded Developer', 'Full Stack Engineer'],
      minimumLevel: 'Fresher',
      maximumLevel: 'Senior',
      createdAt: now,
    },
    topics: [
      {
        id: 'os-processes-threads',
        learningPathId: 'template-os',
        parentId: null,
        title: 'Processes & Threads',
        description: 'Basic execution units of operating systems.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-pcb',
        learningPathId: 'template-os',
        parentId: 'os-processes-threads',
        title: 'Thread Lifecycle & PCB',
        description: 'Process Control Block properties and context.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-context-switching',
        learningPathId: 'template-os',
        parentId: 'os-processes-threads',
        title: 'Context Switching',
        description: 'Saving and restoring register state.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-cpu-scheduling',
        learningPathId: 'template-os',
        parentId: null,
        title: 'CPU Scheduling',
        description: 'Resource sharing algorithms.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-preemption',
        learningPathId: 'template-os',
        parentId: 'os-cpu-scheduling',
        title: 'Preemptive/Non-preemptive',
        description: 'Cooperative vs force context interrupt scheduling.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-schedulers',
        learningPathId: 'template-os',
        parentId: 'os-cpu-scheduling',
        title: 'Round Robin, SJF',
        description: 'Shortest Job First, First-In-First-Out, and time-slice scheduling.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-memory-management',
        learningPathId: 'template-os',
        parentId: null,
        title: 'Memory Management',
        description: 'Physical and virtual memory management systems.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-virtual-paging',
        learningPathId: 'template-os',
        parentId: 'os-memory-management',
        title: 'Virtual Memory/Paging',
        description: 'Translating logical addresses, page tables, and fragmentation.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-tlb',
        learningPathId: 'template-os',
        parentId: 'os-memory-management',
        title: 'TLB',
        description: 'Translation Lookaside Buffer caches.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-page-replacement',
        learningPathId: 'template-os',
        parentId: 'os-memory-management',
        title: 'Page Replacement',
        description: 'LRU, FIFO, and Optimal replacement algorithms.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-concurrency-sync',
        learningPathId: 'template-os',
        parentId: null,
        title: 'Concurrency & Sync',
        description: 'Managing parallel code execution and shared resources.',
        order: 3,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-race-conditions',
        learningPathId: 'template-os',
        parentId: 'os-concurrency-sync',
        title: 'Race Conditions',
        description: 'Critical sections and data consistency hazards.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-mutex-semaphore',
        learningPathId: 'template-os',
        parentId: 'os-concurrency-sync',
        title: 'Mutexes/Semaphores',
        description: 'Locks, binary semaphores, and counting semaphores.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'os-deadlocks',
        learningPathId: 'template-os',
        parentId: 'os-concurrency-sync',
        title: 'Deadlocks',
        description: 'Mutual exclusion, hold and wait, no preemption, and circular wait.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
    ],
    notes: [],
    snippets: [],
    resources: [],
  },
  {
    version: 1,
    type: 'learning-path',
    learningPath: {
      id: 'template-oop',
      title: 'Object-Oriented Programming',
      description: 'Master classes, objects, the four pillars, SOLID design principles, and patterns.',
      icon: 'Box',
      color: '#a78bfa',
      targetRoles: ['Software Engineer', 'Full Stack Engineer', 'Backend Engineer'],
      minimumLevel: 'Fresher',
      maximumLevel: 'Senior',
      createdAt: now,
    },
    topics: [
      {
        id: 'oop-classes-objects',
        learningPathId: 'template-oop',
        parentId: null,
        title: 'Classes & Objects',
        description: 'Basic blueprints and instances.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-ctors',
        learningPathId: 'template-oop',
        parentId: 'oop-classes-objects',
        title: 'Constructors',
        description: 'Object creation, initialization, and destructors.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-access-modifiers',
        learningPathId: 'template-oop',
        parentId: 'oop-classes-objects',
        title: 'Access Modifiers',
        description: 'Scope control: public, private, protected, and package levels.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-four-pillars',
        learningPathId: 'template-oop',
        parentId: null,
        title: 'The Four Pillars',
        description: 'Fundamental object-oriented paradigms.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-encapsulation',
        learningPathId: 'template-oop',
        parentId: 'oop-four-pillars',
        title: 'Encapsulation',
        description: 'Data hiding and wrapping methods/attributes.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-inheritance',
        learningPathId: 'template-oop',
        parentId: 'oop-four-pillars',
        title: 'Inheritance',
        description: 'Reusability across parent and child scopes.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-polymorphism',
        learningPathId: 'template-oop',
        parentId: 'oop-four-pillars',
        title: 'Polymorphism',
        description: 'Compile-time overloading vs runtime method overriding.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-abstraction',
        learningPathId: 'template-oop',
        parentId: 'oop-four-pillars',
        title: 'Abstraction',
        description: 'Interfaces, abstract classes, and hiding internal details.',
        order: 3,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-solid',
        learningPathId: 'template-oop',
        parentId: null,
        title: 'SOLID Principles',
        description: 'Durable and maintainable software architecture designs.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-solid-s-o',
        learningPathId: 'template-oop',
        parentId: 'oop-solid',
        title: 'Single Responsibility',
        description: 'A class should have only one reason to change, Open/Closed principle.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-solid-l-i-d',
        learningPathId: 'template-oop',
        parentId: 'oop-solid',
        title: 'Liskov Substitution',
        description: 'Subtypes must be substitutable for their base types, Interface Segregation, and Dependency Inversion.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-patterns',
        learningPathId: 'template-oop',
        parentId: null,
        title: 'Design Patterns',
        description: 'Reusable templates for common architectural problems.',
        order: 3,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-pattern-creational',
        learningPathId: 'template-oop',
        parentId: 'oop-patterns',
        title: 'Creational Patterns',
        description: 'Singleton, Factory, Builder, and Prototype.',
        order: 0,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-pattern-structural',
        learningPathId: 'template-oop',
        parentId: 'oop-patterns',
        title: 'Structural Patterns',
        description: 'Adapter, Decorator, Facade, and Proxy.',
        order: 1,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'oop-pattern-behavioral',
        learningPathId: 'template-oop',
        parentId: 'oop-patterns',
        title: 'Behavioral Patterns',
        description: 'Observer, Strategy, State, and Command.',
        order: 2,
        status: 'not_started',
        needsRevision: false,
        createdAt: now,
        updatedAt: now,
      },
    ],
    notes: [],
    snippets: [],
    resources: [],
  },
];
