export const rawTopics = [
  // Block 1: Networking & Web APIs
  {
    id: 'networking',
    parentId: null,
    title: 'Networking & Web APIs',
    description: 'Networking fundamentals for frontend',
    order: 5,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'http',
    parentId: 'networking',
    title: 'HTTP',
    description: 'HTTP fundamentals',
    order: 0,
    status: 'interview_ready' as const,
    needsRevision: true,
  },
  {
    id: 'https',
    parentId: 'networking',
    title: 'HTTPS',
    description: 'Secure HTTP',
    order: 1,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'http-methods',
    parentId: 'http',
    title: 'HTTP Methods',
    description: 'GET, POST, PUT, PATCH, DELETE',
    order: 0,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'status-codes',
    parentId: 'http',
    title: 'HTTP Status Codes',
    description: '1xx-5xx',
    order: 1,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'headers',
    parentId: 'http',
    title: 'HTTP Headers',
    description: 'Request & Response headers',
    order: 2,
    status: 'interview_ready' as const,
    needsRevision: true,
  },
  {
    id: 'rest',
    parentId: 'networking',
    title: 'REST APIs',
    description: 'REST architecture',
    order: 2,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'graphql',
    parentId: 'networking',
    title: 'GraphQL',
    description: 'GraphQL basics',
    order: 3,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'fetch-api',
    parentId: 'networking',
    title: 'Fetch API',
    description: 'Modern browser API',
    order: 4,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'abort-controller',
    parentId: 'fetch-api',
    title: 'AbortController',
    description: 'Cancel network requests',
    order: 0,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'cors',
    parentId: 'networking',
    title: 'CORS',
    description: 'Cross Origin Resource Sharing',
    order: 5,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'cookies',
    parentId: 'networking',
    title: 'Cookies',
    description: 'Browser cookies',
    order: 6,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'local-auth',
    parentId: 'networking',
    title: 'JWT Authentication',
    description: 'Token based authentication',
    order: 7,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'oauth',
    parentId: 'networking',
    title: 'OAuth 2.0',
    description: 'Third-party authentication',
    order: 8,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'caching',
    parentId: 'networking',
    title: 'Caching',
    description: 'Browser and HTTP caching',
    order: 9,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'cache-control',
    parentId: 'caching',
    title: 'Cache-Control',
    description: 'Cache directives',
    order: 0,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'etag',
    parentId: 'caching',
    title: 'ETag',
    description: 'Conditional requests',
    order: 1,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'websocket',
    parentId: 'networking',
    title: 'WebSocket',
    description: 'Full duplex communication',
    order: 10,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'sse',
    parentId: 'networking',
    title: 'Server Sent Events',
    description: 'One-way streaming',
    order: 11,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'file-upload',
    parentId: 'networking',
    title: 'File Upload',
    description: 'Multipart upload',
    order: 12,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'retry',
    parentId: 'networking',
    title: 'Retry & Backoff',
    description: 'Retry failed requests',
    order: 13,
    status: 'not_started' as const,
    needsRevision: false,
  },

  // Block 2: HTML & CSS
  {
    id: 'html',
    parentId: null,
    title: 'HTML',
    description: 'HTML fundamentals',
    order: 2,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'semantic-html',
    parentId: 'html',
    title: 'Semantic HTML',
    description: 'Semantic elements',
    order: 0,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'forms',
    parentId: 'html',
    title: 'Forms',
    description: 'HTML Forms',
    order: 1,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'accessibility-html',
    parentId: 'html',
    title: 'Accessibility Basics',
    description: 'ARIA and semantics',
    order: 2,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'seo',
    parentId: 'html',
    title: 'SEO Basics',
    description: 'Metadata and indexing',
    order: 3,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'css',
    parentId: null,
    title: 'CSS',
    description: 'CSS roadmap',
    order: 3,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'selectors',
    parentId: 'css',
    title: 'Selectors',
    description: 'CSS selectors',
    order: 0,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'specificity',
    parentId: 'css',
    title: 'Specificity',
    description: 'Cascade priority',
    order: 1,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'box-model',
    parentId: 'css',
    title: 'Box Model',
    description: 'Content, padding, border, margin',
    order: 2,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'positioning',
    parentId: 'css',
    title: 'Positioning',
    description: 'Static, relative, absolute, fixed, sticky',
    order: 3,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'flexbox',
    parentId: 'css',
    title: 'Flexbox',
    description: 'One-dimensional layouts',
    order: 4,
    status: 'interview_ready' as const,
    needsRevision: true,
  },
  {
    id: 'grid',
    parentId: 'css',
    title: 'CSS Grid',
    description: 'Two-dimensional layouts',
    order: 5,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'responsive',
    parentId: 'css',
    title: 'Responsive Design',
    description: 'Media queries',
    order: 6,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'animations',
    parentId: 'css',
    title: 'Animations',
    description: 'Transitions and keyframes',
    order: 7,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'container-queries',
    parentId: 'css',
    title: 'Container Queries',
    description: 'Modern responsive CSS',
    order: 8,
    status: 'not_started' as const,
    needsRevision: false,
  },

  // Block 3: TypeScript
  {
    id: 'typescript',
    parentId: null,
    title: 'TypeScript',
    description: 'Type-safe JavaScript',
    order: 4,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'ts-basics',
    parentId: 'typescript',
    title: 'TypeScript Fundamentals',
    description: 'Primitive and basic types',
    order: 0,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'primitive-types',
    parentId: 'ts-basics',
    title: 'Primitive Types',
    description: 'string, number, boolean',
    order: 0,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'interfaces',
    parentId: 'typescript',
    title: 'Interfaces',
    description: 'Contracts for objects',
    order: 1,
    status: 'interview_ready' as const,
    needsRevision: true,
  },
  {
    id: 'type-aliases',
    parentId: 'typescript',
    title: 'Type Aliases',
    description: 'Reusable type definitions',
    order: 2,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'generics',
    parentId: 'typescript',
    title: 'Generics',
    description: 'Reusable typed components',
    order: 3,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'utility-types',
    parentId: 'typescript',
    title: 'Utility Types',
    description: 'Partial, Pick, Omit, Readonly...',
    order: 4,
    status: 'interview_ready' as const,
    needsRevision: true,
  },
  {
    id: 'partial',
    parentId: 'utility-types',
    title: 'Partial',
    description: 'Makes all properties optional',
    order: 0,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'pick',
    parentId: 'utility-types',
    title: 'Pick',
    description: 'Select subset of properties',
    order: 1,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'omit',
    parentId: 'utility-types',
    title: 'Omit',
    description: 'Exclude properties',
    order: 2,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'readonly',
    parentId: 'utility-types',
    title: 'Readonly',
    description: 'Immutable properties',
    order: 3,
    status: 'interview_ready' as const,
    needsRevision: false,
  },
  {
    id: 'mapped-types',
    parentId: 'typescript',
    title: 'Mapped Types',
    description: 'Transform existing types',
    order: 5,
    status: 'learning' as const,
    needsRevision: false,
  },
  {
    id: 'conditional-types',
    parentId: 'typescript',
    title: 'Conditional Types',
    description: 'Type logic',
    order: 6,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'infer',
    parentId: 'conditional-types',
    title: 'infer',
    description: 'Infer types',
    order: 0,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'declaration-files',
    parentId: 'typescript',
    title: 'Declaration Files',
    description: 'd.ts files',
    order: 7,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'advanced-generics',
    parentId: 'typescript',
    title: 'Advanced Generics',
    description: 'Constraints & defaults',
    order: 8,
    status: 'not_started' as const,
    needsRevision: false,
  },
  {
    id: 'type-inference',
    parentId: 'typescript',
    title: 'Type Inference',
    description: 'Compiler inference',
    order: 9,
    status: 'learning' as const,
    needsRevision: false,
  },
];

export const rawNotes = [
  {
    id: 'note-http',
    topicId: 'http',
    markdown: '# HTTP\n\nUnderstand request-response lifecycle, methods, headers and status codes.',
  },
  {
    id: 'note-cors',
    topicId: 'cors',
    markdown: '# CORS\n\nBrowser security model and preflight requests.',
  },
  {
    id: 'note-flexbox',
    topicId: 'flexbox',
    markdown: '# Flexbox\n\nUsed extensively for one-dimensional layouts.',
  },
  {
    id: 'note-grid',
    topicId: 'grid',
    markdown: '# CSS Grid\n\nPowerful two-dimensional layout system.',
  },
  {
    id: 'note-utility',
    topicId: 'utility-types',
    markdown: '# Utility Types\n\nCovered Partial, Pick, Omit and Readonly in depth.',
  },
  {
    id: 'note-generics',
    topicId: 'generics',
    markdown: '# Generics\n\nNeed deeper practice with constraints and inference.',
  },
];

export const rawSnippets = [
  {
    id: 'snippet-fetch',
    topicId: 'fetch-api',
    filename: 'fetch.ts',
    language: 'typescript',
    code: "const res = await fetch('/api/users');\nconst data = await res.json();",
  },
  {
    id: 'snippet-flex',
    topicId: 'flexbox',
    filename: 'flex.css',
    language: 'css',
    code: '.container{display:flex;justify-content:center;align-items:center;}',
  },
  {
    id: 'snippet-partial',
    topicId: 'partial',
    filename: 'partial.ts',
    language: 'typescript',
    code: 'interface User { id:number; name:string }\ntype PartialUser = Partial<User>;',
  },
  {
    id: 'snippet-generic',
    topicId: 'generics',
    filename: 'generic.ts',
    language: 'typescript',
    code: 'function identity<T>(value:T):T{return value;}',
  },
];

export const rawResources = [
  {
    id: 'resource-mdn-fetch',
    topicId: 'fetch-api',
    title: 'MDN Fetch API',
    type: 'Documentation' as const,
    url: 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API',
  },
  {
    id: 'resource-http',
    topicId: 'http',
    title: 'HTTP MDN',
    type: 'Documentation' as const,
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP',
  },
  {
    id: 'resource-flexbox',
    topicId: 'flexbox',
    title: 'CSS Tricks Flexbox Guide',
    type: 'Documentation' as const,
    url: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
  },
  {
    id: 'resource-grid',
    topicId: 'grid',
    title: 'CSS Tricks Grid Guide',
    type: 'Documentation' as const,
    url: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
  },
  {
    id: 'resource-ts',
    topicId: 'typescript',
    title: 'TypeScript Handbook',
    type: 'Documentation' as const,
    url: 'https://www.typescriptlang.org/docs/',
  },
  {
    id: 'resource-utility',
    topicId: 'utility-types',
    title: 'Utility Types',
    type: 'Documentation' as const,
    url: 'https://www.typescriptlang.org/docs/handbook/utility-types.html',
  },
];
